### ISSUE TITLE
`Reason: await is not defined` when using with Knip

### ISSUE THREAD

**Issue by sergiodxa** [mcansh/vite-plugin-svg-sprite#23]
I'm using [Knip](https://knip.dev) in a project, and I configured it to use its Vite plugin, when I try to run it I get:

```sh
> knip

Analyzing workspace ....
Error loading /<PATH>/vite.config.ts
Reason: await is not defined
```

The error goes away if I remove `@mcansh/vite-svg-sprite-plugin`.

**Comment by mcansh** [comment]
hey @sergiodxa looks like this "known issue" with knip and jiti which it uses to load ts, so you'll need to do one of the following https://knip.dev/reference/known-issues#ts-config-files-using-esm-features

**Comment by sergiodxa** [comment]
In case someone has the same issue, I was not able to solve it using the Knip docs, but when I did `bun run --bun unused` to run Knip (unused is my package.json script) it started to work perfectly since Bun does support top level await.
