### ISSUE TITLE
add to the configuration the ability to pass custom `svgRegex`

### ISSUE THREAD

**Issue by mcansh** [mcansh/vite-plugin-svg-sprite#40]
because not always all SVG files need to be added to the sprite

_Originally posted by @kucherenko-ae in https://github.com/mcansh/vite-plugin-svg-sprite/issues/38#issuecomment-2092382116_

**Comment by mcansh** [comment]
what imported svg files would you not want to be included? this should only account for ones that would be base64 encoded and inlined. 

i can surely add the option to exclude certain ones, but you can get the same base64/inlined result by appending `?inline` to the end of the filename in the import

**Comment by kucherenko-ae** [comment]
hello
Sometimes need to use a SVG file like src for an image. logo or other disposable element.
The current version of plugin also includes these files in the sprite.
I little edited your plugin in my dev version and added the support I'm talking about. This allowed me to specify the desired directory in which the icons for the sprite were stored.

Just for example, changes:

<img width="699" alt="image" src="https://github.com/mcansh/vite-plugin-svg-sprite/assets/40565571/7bfac560-79ec-4e81-a447-8afbe00ed8ab">
<img width="452" alt="image" src="https://github.com/mcansh/vite-plugin-svg-sprite/assets/40565571/2758477f-17c8-48ed-b3f7-e453826e67e2">
<img width="354" alt="image" src="https://github.com/mcansh/vite-plugin-svg-sprite/assets/40565571/04681477-76c2-4a43-bac1-b08da7b83e2c">
<img width="339" alt="image" src="https://github.com/mcansh/vite-plugin-svg-sprite/assets/40565571/364c8db1-eb9a-42c2-a052-c9ba3b747c81">

**Comment by kucherenko-ae** [comment]
or, alternatively, skip icon if the import includes `?url`

for example:
`import icon from './assets/icon.svg?url'`
